name: Laravel CI/CD
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with: { php-version: "8.2" }
      - run: composer install
      - run: cp .env.example .env && php artisan key:generate
      - run: php artisan test
  deploy:
    needs: tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          script: |
            cd /home/ubuntu/work/api-swen && git pull origin main
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            # cd /home/ubuntu/work/api-swen && git pull origin main && composer install --no-dev
            # php artisan migrate --force
            # php artisan config:cache
